// moodData.ts
export type Mood = {
  label: string; // 문자열로 정의
  color: string;
  pleasantness: number;
  energy: number;
};

const colorMap: { [key: string]: string } = {
  빨간색: "#EE5D50",
  노란색: "#FFDE57",
  파란색: "#6AD2FF",
  초록색: "#35D28A",
};

export const moodData: Mood[] = [
  { label: "격분한", color: colorMap["빨간색"], pleasantness: 1, energy: 10 },
  {
    label: "공황에 빠진",
    color: colorMap["빨간색"],
    pleasantness: 2,
    energy: 10,
  },
  {
    label: "스트레스 받는",
    color: colorMap["빨간색"],
    pleasantness: 3,
    energy: 10,
  },
  { label: "초조한", color: colorMap["빨간색"], pleasantness: 4, energy: 10 },
  { label: "충격받은", color: colorMap["빨간색"], pleasantness: 5, energy: 10 },
  { label: "놀란", color: colorMap["노란색"], pleasantness: 6, energy: 10 },
  { label: "긍정적인", color: colorMap["노란색"], pleasantness: 7, energy: 10 },
  { label: "흥겨운", color: colorMap["노란색"], pleasantness: 8, energy: 10 },
  {
    label: "아주 신나는",
    color: colorMap["노란색"],
    pleasantness: 9,
    energy: 10,
  },
  { label: "황홀한", color: colorMap["노란색"], pleasantness: 10, energy: 10 },

  { label: "격노한", color: colorMap["빨간색"], pleasantness: 1, energy: 9 },
  {
    label: "몹시 화가 난",
    color: colorMap["빨간색"],
    pleasantness: 2,
    energy: 9,
  },
  { label: "좌절한", color: colorMap["빨간색"], pleasantness: 3, energy: 9 },
  {
    label: "신경이 날카로운",
    color: colorMap["빨간색"],
    pleasantness: 4,
    energy: 9,
  },
  {
    label: "망연자실한",
    color: colorMap["빨간색"],
    pleasantness: 5,
    energy: 9,
  },
  { label: "들뜬", color: colorMap["노란색"], pleasantness: 6, energy: 9 },
  { label: "쾌활한", color: colorMap["노란색"], pleasantness: 7, energy: 9 },
  {
    label: "동기 부여된",
    color: colorMap["노란색"],
    pleasantness: 8,
    energy: 9,
  },
  {
    label: "영감을 받은",
    color: colorMap["노란색"],
    pleasantness: 9,
    energy: 9,
  },
  {
    label: "의기양양한",
    color: colorMap["노란색"],
    pleasantness: 10,
    energy: 9,
  },

  {
    label: "화가 치밀어 오른",
    color: colorMap["빨간색"],
    pleasantness: 1,
    energy: 8,
  },
  { label: "겁먹은", color: colorMap["빨간색"], pleasantness: 2, energy: 8 },
  { label: "화난", color: colorMap["빨간색"], pleasantness: 3, energy: 8 },
  { label: "초조한", color: colorMap["빨간색"], pleasantness: 4, energy: 8 },
  {
    label: "안절부절못하는",
    color: colorMap["빨간색"],
    pleasantness: 5,
    energy: 8,
  },
  {
    label: "기운이 넘치는",
    color: colorMap["노란색"],
    pleasantness: 6,
    energy: 8,
  },
  { label: "활발한", color: colorMap["노란색"], pleasantness: 7, energy: 8 },
  { label: "흥분한", color: colorMap["노란색"], pleasantness: 8, energy: 8 },
  { label: "낙관적인", color: colorMap["노란색"], pleasantness: 9, energy: 8 },
  { label: "열광하는", color: colorMap["노란색"], pleasantness: 10, energy: 8 },

  { label: "불안한", color: colorMap["빨간색"], pleasantness: 1, energy: 7 },
  { label: "우려하는", color: colorMap["빨간색"], pleasantness: 2, energy: 7 },
  { label: "근심하는", color: colorMap["빨간색"], pleasantness: 3, energy: 7 },
  { label: "짜증나는", color: colorMap["빨간색"], pleasantness: 4, energy: 7 },
  { label: "거슬리는", color: colorMap["빨간색"], pleasantness: 5, energy: 7 },
  {
    label: "만족스러운",
    color: colorMap["노란색"],
    pleasantness: 6,
    energy: 7,
  },
  { label: "집중하는", color: colorMap["노란색"], pleasantness: 7, energy: 7 },
  { label: "행복한", color: colorMap["노란색"], pleasantness: 8, energy: 7 },
  {
    label: "자랑스러운",
    color: colorMap["노란색"],
    pleasantness: 9,
    energy: 7,
  },
  { label: "짜릿한", color: colorMap["노란색"], pleasantness: 10, energy: 7 },

  { label: "불쾌한", color: colorMap["빨간색"], pleasantness: 1, energy: 6 },
  { label: "골치 아픈", color: colorMap["빨간색"], pleasantness: 2, energy: 6 },
  { label: "염려하는", color: colorMap["빨간색"], pleasantness: 3, energy: 6 },
  {
    label: "마음이 불편한",
    color: colorMap["빨간색"],
    pleasantness: 4,
    energy: 6,
  },
  { label: "언짢은", color: colorMap["빨간색"], pleasantness: 5, energy: 6 },
  { label: "유쾌한", color: colorMap["노란색"], pleasantness: 6, energy: 6 },
  { label: "기쁜", color: colorMap["노란색"], pleasantness: 7, energy: 6 },
  { label: "희망찬", color: colorMap["노란색"], pleasantness: 8, energy: 6 },
  { label: "재미있는", color: colorMap["노란색"], pleasantness: 9, energy: 6 },
  {
    label: "더없이 행복한",
    color: colorMap["노란색"],
    pleasantness: 10,
    energy: 6,
  },

  { label: "역겨운", color: colorMap["파란색"], pleasantness: 1, energy: 5 },
  { label: "침울한", color: colorMap["파란색"], pleasantness: 2, energy: 5 },
  {
    label: "실망스러운",
    color: colorMap["파란색"],
    pleasantness: 3,
    energy: 5,
  },
  { label: "의욕 없는", color: colorMap["파란색"], pleasantness: 4, energy: 5 },
  { label: "냉담한", color: colorMap["파란색"], pleasantness: 5, energy: 5 },
  { label: "속 편한", color: colorMap["초록색"], pleasantness: 6, energy: 5 },
  { label: "태평한", color: colorMap["초록색"], pleasantness: 7, energy: 5 },
  { label: "자족하는", color: colorMap["초록색"], pleasantness: 8, energy: 5 },
  { label: "다정한", color: colorMap["초록색"], pleasantness: 9, energy: 5 },
  { label: "충만한", color: colorMap["초록색"], pleasantness: 10, energy: 5 },

  { label: "비관적인", color: colorMap["파란색"], pleasantness: 1, energy: 4 },
  { label: "시무룩한", color: colorMap["파란색"], pleasantness: 2, energy: 4 },
  { label: "낙담한", color: colorMap["파란색"], pleasantness: 3, energy: 4 },
  { label: "슬픈", color: colorMap["파란색"], pleasantness: 4, energy: 4 },
  { label: "지루한", color: colorMap["파란색"], pleasantness: 5, energy: 4 },
  { label: "평온한", color: colorMap["초록색"], pleasantness: 6, energy: 4 },
  { label: "안전한", color: colorMap["초록색"], pleasantness: 7, energy: 4 },
  {
    label: "만족스러운",
    color: colorMap["초록색"],
    pleasantness: 8,
    energy: 4,
  },
  { label: "감사하는", color: colorMap["초록색"], pleasantness: 9, energy: 4 },
  { label: "감동적인", color: colorMap["초록색"], pleasantness: 10, energy: 4 },

  { label: "소외된", color: colorMap["파란색"], pleasantness: 1, energy: 3 },
  { label: "비참한", color: colorMap["파란색"], pleasantness: 2, energy: 3 },
  { label: "쓸쓸한", color: colorMap["파란색"], pleasantness: 3, energy: 3 },
  { label: "기죽은", color: colorMap["파란색"], pleasantness: 4, energy: 3 },
  { label: "피곤한", color: colorMap["파란색"], pleasantness: 5, energy: 3 },
  { label: "여유로운", color: colorMap["초록색"], pleasantness: 6, energy: 3 },
  { label: "차분한", color: colorMap["초록색"], pleasantness: 7, energy: 3 },
  { label: "편안한", color: colorMap["초록색"], pleasantness: 8, energy: 3 },
  { label: "축복받은", color: colorMap["초록색"], pleasantness: 9, energy: 3 },
  { label: "안정적인", color: colorMap["초록색"], pleasantness: 10, energy: 3 },

  {
    label: "의기소침한",
    color: colorMap["파란색"],
    pleasantness: 1,
    energy: 2,
  },
  { label: "우울한", color: colorMap["파란색"], pleasantness: 2, energy: 2 },
  { label: "뚱한", color: colorMap["파란색"], pleasantness: 3, energy: 2 },
  {
    label: "기진맥진한",
    color: colorMap["파란색"],
    pleasantness: 4,
    energy: 2,
  },
  { label: "지친", color: colorMap["파란색"], pleasantness: 5, energy: 2 },
  { label: "한가로운", color: colorMap["초록색"], pleasantness: 6, energy: 2 },
  {
    label: "생각에 잠긴",
    color: colorMap["초록색"],
    pleasantness: 7,
    energy: 2,
  },
  { label: "평화로운", color: colorMap["초록색"], pleasantness: 8, energy: 2 },
  { label: "편한", color: colorMap["초록색"], pleasantness: 9, energy: 2 },
  {
    label: "근심 걱정 없는",
    color: colorMap["초록색"],
    pleasantness: 10,
    energy: 2,
  },

  { label: "절망한", color: colorMap["파란색"], pleasantness: 1, energy: 1 },
  { label: "가망 없는", color: colorMap["파란색"], pleasantness: 2, energy: 1 },
  { label: "고독한", color: colorMap["파란색"], pleasantness: 3, energy: 1 },
  { label: "소모된", color: colorMap["파란색"], pleasantness: 4, energy: 1 },
  { label: "진이 빠진", color: colorMap["파란색"], pleasantness: 5, energy: 1 },
  { label: "나른한", color: colorMap["초록색"], pleasantness: 6, energy: 1 },
  { label: "흐뭇한", color: colorMap["초록색"], pleasantness: 7, energy: 1 },
  { label: "고요한", color: colorMap["초록색"], pleasantness: 8, energy: 1 },
  { label: "안락한", color: colorMap["초록색"], pleasantness: 9, energy: 1 },
  { label: "안온한", color: colorMap["초록색"], pleasantness: 10, energy: 1 },
];
